[default]
DEBUG = false
# SQLALCHEMY_DATABASE_URI = 'sqlite:///development.db'
EXTENSIONS = [
    "web_gear_sample.domain.dashboard:init_app"
]

[development]
DEBUG = true
TEMPLATES_AUTO_RELOAD = true
EXTENSIONS = [
    "flask_debugtoolbar:DebugToolbarExtension",
    "dynaconf_merge_unique"  # to reuse extensions list from [default]
]

[production]

[testing]
